//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourPlayer
    {
        public string Players1 { get; set; }
        public Nullable<int> Score1 { get; set; }
        public string Players2 { get; set; }
        public Nullable<int> Score2 { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
    }
}
